### ISSUE TITLE
How create new user (access) using API ??

### ISSUE THREAD

**Issue by rgchurion** [dave-p/TVH-API-docs#3]
Hi, can you help me?, i want to create a new user from php code using API, how can i do it?, i use api for querys, extrat info from tvheadend, but, how can i create one new user?.

Thanks very much.

RobertG.

**Comment by dave-p** [comment]
I haven't tested it, but you should be able to use api/access/entry/create. Pass a parameter 'conf' containing the JSON object describing the user, you can use api/access/entry/grid to see the details of existing users.

User passwords are stored separately; use api/passwd/entry/create to add a password for your new user.

**Comment by creited** [comment]
@rgchurion, could you reach the goal?

I am looking exactally this feature, but I'm noob into programing.

Any help would be really appreciated.

**Comment by 3v3rm4rt3lL** [comment]
I need the same example. I trying to figure it out.
